services:
  speedtest:
      container_name: speedtest-tracker
      image: henrywhitaker3/speedtest-tracker:dev-arm
      ports:
        - 9000:80
      volumes:
        - data:/config
      environment:
        - OOKLA_EULA_GDPR=true
      logging:
          driver: "json-file"
          options:
              max-file: "10"
              max-size: "200k"
      restart: unless-stopped

volumes:
  data: