services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - WATCHTOWER_CLEANUP=true

  watchtower-once:
    image: containrrr/watchtower:latest
    container_name: watchtower-once
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
